apiVersion: apps/v1
kind: Deployment
metadata:
  name: account-deployment
  namespace: awg
  labels:
    app: awg-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: awg-app
  template:
    metadata:
      labels:
        app: awg-app
    spec:
      containers:
      - name: account
        image: ghcr.io/ukrvalik/account:0.1
        env:
        - name: JWT_SECRET
          valueFrom:
            secretKeyRef:
              name: jwt
              key: jwt_secret
        - name: AMQP_EXCHANGE
          valueFrom:
            secretKeyRef:
              name: rmq-account
              key: exchange
        - name: AMQP_QUEUE
          valueFrom:
            secretKeyRef:
              name: rmq-account
              key: queue
        - name: AMQP_USER
          valueFrom:
            secretKeyRef:
              name: rabbitmq-admin
              key: user
        - name: AMQP_PASSWORD
          valueFrom:
            secretKeyRef:
              name: rabbitmq-admin
              key: pass
        - name: AMQP_HOSTNAME
          valueFrom:
            secretKeyRef:
              name: rmq-account
              key: hostname
        - name: MONGO_LOGIN
          valueFrom:
            secretKeyRef:
              name: mongo-user
              key: mongo_login
        - name: MONGO_PASSWORD
          valueFrom:
            secretKeyRef: 
              name: mongo-user
              key: mongo_password
        - name: MONGO_HOST
          valueFrom:
            secretKeyRef:
              name: mongo-account
              key: host
        - name: MONGO_DATABASE
          valueFrom:
            secretKeyRef:
              name: mongo-account
              key: database
        imagePullPolicy: always # prod
      imagePullSecrets:
      - name: regcred
      serviceAccountName: default
