apiVersion: v1
kind: Service
metadata:
  name: api-service
  namespace: awg
spec:
  type: LoadBalancer
  selector:
    app: awg-app
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000