apiVersion: apps/v1
kind: Deployment
metadata:
  name: vocabulary-deployment
  namespace: awg
  labels:
    app: awg-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: awg-app
  template:
    metadata:
      labels:
        app: awg-app
    spec:
      containers:
      - name: vocabulary
        image: vocabulary:1.0
        env:
        - name: AMQP_EXCHANGE
          value: "awg"
        - name: AMQP_QUEUE
          value: "awg.vocabulary"
        - name: AMQP_USER
          valueFrom:
            secretKeyRef:
              name: rabbitmq-admin
              key: user
        - name: AMQP_PASSWORD
          valueFrom:
            secretKeyRef:
              name: rabbitmq-admin
              key: pass
        - name: AMQP_HOSTNAME
          value: "10.98.210.7"
        - name: MONGO_LOGIN
          valueFrom:
            secretKeyRef:
              name: mongo-user
              key: mongo_login
        - name: MONGO_PASSWORD
          valueFrom:
            secretKeyRef: 
              name: mongo-user
              key: mongo_password
        - name: MONGO_HOST
          value: "another-word-game.vvhoo.mongodb.net"
        - name: MONGO_DATABASE
          value: "vocabulary"
#        imagePullPolicy: always # prod
        imagePullPolicy: Never
      serviceAccountName: default
