name: CD-DEV-SERVICES

on: workflow_dispatch

jobs:
  deploy-apps:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: Install doctl
        uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DO_TOKEN }}

      - name: Connect to cluster
        run: doctl kubernetes cluster kubeconfig save ${{ secrets.DEV_CLUSTER_ID }}

      - name: Use awg namespace
        run: kubectl config set-context --current --namespace awg

      - name: Deploy Account
        working-directory: awg-backend
        run: kubectl apply -f deploy/account-deploy-k8s.yml
      
      - name: Deploy Api
        working-directory: awg-backend
        run: kubectl apply -f deploy/api-deploy-k8s.yml
      
      - name: Deploy Game
        working-directory: awg-backend
        run: kubectl apply -f deploy/game-deploy-k8s.yml

      - name: Deploy Vocabulary
        working-directory: awg-backend
        run: kubectl apply -f deploy/vocabulary-deploy-k8s.yml

      - run: sleep 20s

      - name: Verify deploy
        run: kubectl get pods
