name: Node.js CI

on:
  pull_request:
    branches: [ "main" ]

env:
  REGISTRY: ghcr.io
  API_IMAGE_NAME: api

jobs:
  run-tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x]

    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
        cache-dependency-path: './awg-backend/package-lock.json'

    - name: Test Account
      working-directory: 'awg-backend'
      run: |
        npm ci
        npm run account:test

  build-and-push:
    runs-on: ubuntu-latest
    needs: run-tests
    strategy:
      matrix:
        node-version: [18.x]

    steps:
      - uses: actions/checkout@v4
      - name: Log in to the Container registry
        uses: docker/login-action@65b78e6e13532edd9afa3aa52ac7964289d1a9c1
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.CR_GITHUB_TOKEN }}

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
          cache-dependency-path: './awg-backend/package-lock.json'
      
      - uses: nrwl/nx-set-shas@v4

      - name: Build and push Account
        working-directory: 'awg-backend'
        run: |
          npm ci
          npx nx build api
          docker build -t api:0.0.0 -f docker/Dockerfile-api .
          docker push ${{ env.REGISTRY }}/UkrValik/api:0.0.0
